nginx:
  build: ./
  restart: always
  mem_limit: 1g
  env_file:
    - .env
  ports:
    - 80:80
    - 443:443
  links:
    - navigation:navigation
    - instances:instances
    - images:images
navigation:
  image: joyent/webconsole-navigation:master
  restart: always
  mem_limit: 128m
  expose:
    - 8080
  env_file:
    - .auth.env
    - .navigation.env
  environment:
    - PORT=8080
    - BASE_URL=https://localhost
    - NODE_ENV=production
  volumes:
    - ./data:/opt/app/data:ro
instances:
  image: joyent/webconsole-instances:master
  restart: always
  mem_limit: 128m
  expose:
    - 8081
  env_file:
    - .auth.env
    - .instances.env
  environment:
    - PORT=8081
    - BASE_URL=https://localhost
    - COOKIE_DOMAIN=localhost
    - NODE_ENV=production
images:
  image: joyent/webconsole-images:master
  restart: always
  mem_limit: 128m
  expose:
    - 8082
  env_file:
    - .auth.env
    - .images.env
  environment:
    - PORT=8082
    - BASE_URL=https://localhost
    - COOKIE_DOMAIN=localhost
    - NODE_ENV=production
