webconsole-nginx:
  build: ./
  restart: always
  mem_limit: 1g
  env_file:
    - .env
  ports:
    - 80:80
    - 443:443
  links:
    - navigation:navigation
    - instances:instances
instances:
  image: crccheck/hello-world
  restart: always
  mem_limit: 128m
navigation:
  image: crccheck/hello-world
  restart: always
  mem_limit: 128m
